ENV["RAILS_ENV"] ||= "test"
require_relative "../config/environment"
require "rails/test_help"
require_relative "test_helpers/session_test_helper"

module ActiveSupport
  class TestCase
    # Run tests in parallel with specified workers
    parallelize(workers: :number_of_processors)

    # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
    fixtures :all

    # users.yml predates the multi-tenant Company model (it was
    # generated by `rails generate authentication` before Company
    # existed), so its fixture rows have no company_id. Since
    # belongs_to :company is required by default, any save on one of
    # these users (e.g. a password reset) fails validation. Real users
    # created through sign-up or an invite always have a company, so
    # this only ever bites fixture-based tests. Give every companyless
    # fixture user a company before each test runs, rather than editing
    # users.yml directly (its exact content/labels aren't something
    # this project owns or has verified).
    setup do
      if defined?(Company) && defined?(User)
        company = Company.first || Company.create!(name: "Fixture Co")
        User.where(company_id: nil).update_all(company_id: company.id)
      end
    end

    # Add more helper methods to be used by all tests here...
  end
end
